### ISSUE TITLE
Assigning ID the url

### ISSUE THREAD

**Issue by sikhote** [carlyMhayter/infiniteScroll#3]
https://github.com/carlyMhayter/infiniteScroll/blob/cb59464f2e53b283d888cd2db714100c32a03820/script.js#L67

If you need to store data, it is more common practice to store data in data attributes, which is just making an attribute that has `data-some-name`...so you could assign `data-src` the URL.

**Comment by carlyMhayter** [comment]
double check that you don't actually use paletteButton.id
