### ISSUE TITLE
consider moving this function

### ISSUE THREAD

**Issue by sikhote** [carlyMhayter/infiniteScroll#5]
https://github.com/carlyMhayter/infiniteScroll/blob/cb59464f2e53b283d888cd2db714100c32a03820/script.js#L67

it might be helpful to move this function to be outside of the click event, and pass in any necessary things (like the button variable)

**Comment by sikhote** [comment]
line 114, sorry this line is wrong

**Comment by carlyMhayter** [comment]
create functions outside of event listener, then call them inside

**Comment by carlyMhayter** [comment]
moved
